### ISSUE TITLE
remove small helper function: elapsed_ms()

### ISSUE THREAD

**Issue by dennisguse** [krueger-christian/razorAHRS#3]
It is just one line and relies on data that is passed to it.
It is rather confusing.

**Comment by krueger-christian** [comment]
But it is a confusing line boxed into a function with a name that describes what the line does. Removing it would mean to create lines like:

`if(((end.tv_sec - start.tv_sec) * 1000 + (end.tv_usec - start.tv_usec) / 1000) > connect_time_out)`

just to compare it with the current status:
`if(elapsed_ms(t1, t2) > connect_time_out)`

Has the function any bad effect on the performance?

**Comment by dennisguse** [comment]
Nope
